const tableData = [
    {
        Symbol: 'TATAMOTORS EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: true,
        value: '1971.50',
        gainLoss: '100.00',
        Trade: 'Completed',
    },
    {
        Symbol: 'PT EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: false,
        value: '1971.50',
        gainLoss: '-90',
        Trade: 'Completed',
    },
    {
        Symbol: 'GTYTYJB EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: true,
        value: '1971.50',
        gainLoss: '100.00',
        Trade: 'Completed',
    },
    {
        Symbol: 'DFC EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: true,
        value: '1971.50',
        gainLoss: '100.00',
        Trade: 'Completed',
    },
    {
        Symbol: 'EXD C EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: false,
        value: '1971.50',
        gainLoss: '-125',
        Trade: 'Completed',
    },
    {
        Symbol: 'TATAMOTORS EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: true,
        value: '1971.50',
        gainLoss: '100.00',
        Trade: 'Completed',
    },
    {
        Symbol: 'TATAMOTORS EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: false,
        value: '1971.50',
        gainLoss: '-84.4',
        Trade: 'Completed',
    },
    {
        Symbol: 'TATAMOTORS EQ',
        Current: '394.30',
        Today: '+7.65',
        Purchase: '394.30',
        QTY: '15',
        positive: true,
        value: '1971.50',
        gainLoss: '100.00',
        Trade: 'Completed',
    },
]
export default tableData;